import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import '@mantine/core/styles.css';

export const metadata: Metadata = {
  title: "Todo List - App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <header>
            Este es el header
          </header>
          {children}
          <footer>
            Este es el footer
          </footer>
        </MantineProvider>
      </body>
    </html>
  );
}
